apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-inventory-service-deployment
  labels:
    app: rss-inventory-service
    track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rss-inventory-service
      track: stable
  template:
    metadata:
      labels:
        app: rss-inventory-service
        track: stable
    spec:
      containers:
      - name: rss-inventory-service
        image: baronvonfroglok/rss-inventory-service:latest
        ports:
        - containerPort: 8989
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8989
          initialDelaySeconds: 30
          periodSeconds: 30
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: rss-inventory-credentials
              key: url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rss-inventory-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rss-inventory-credentials
              key: password