apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rss-inventory-prometheus-rules
  namespace: rss-inventory
  labels: # one of the app labels will need to be removed. Temp status for debugging
    app: rss-inventory-service 
    job: rss-inventory-service 
    release: kube-prometheus-stack
    app: kube-prometheus-stack
    team: p3
spec:
    groups:
    - name: rss-inventory-SLOs-http_requests_total
      rules:
      - alert: ErrorBudgetBurn
        annotations:
          message: 'High error budget burn for job=rss-inventory (current value: {{ $value }})'
        expr: |
          sum(http_requests_total:burnrate5m{job="rss-inventory"}) > (14.40 * (1-0.99500))
          and
          sum(http_requests_total:burnrate1h{job="rss-inventory"}) > (14.40 * (1-0.99500))
        for: 2m
        labels:
          job: rss-inventory
          severity: critical
      - alert: ErrorBudgetBurn
        annotations:
          message: 'High error budget burn for job=rss-inventory (current value: {{ $value }})'
        expr: |
          sum(http_requests_total:burnrate30m{job="rss-inventory"}) > (6.00 * (1-0.99500))
          and
          sum(http_requests_total:burnrate6h{job="rss-inventory"}) > (6.00 * (1-0.99500))
        for: 15m
        labels:
          job: rss-inventory
          severity: critical
      - alert: ErrorBudgetBurn
        annotations:
          message: 'High error budget burn for job=rss-inventory (current value: {{ $value }})'
        expr: |
          sum(http_requests_total:burnrate2h{job="rss-inventory"}) > (3.00 * (1-0.99500))
          and
          sum(http_requests_total:burnrate1d{job="rss-inventory"}) > (3.00 * (1-0.99500))
        for: 1h
        labels:
          job: rss-inventory
          severity: warning
      - alert: ErrorBudgetBurn
        annotations:
          message: 'High error budget burn for job=rss-inventory (current value: {{ $value }})'
        expr: |
          sum(http_requests_total:burnrate6h{job="rss-inventory"}) > (1.00 * (1-0.99500))
          and
          sum(http_requests_total:burnrate3d{job="rss-inventory"}) > (1.00 * (1-0.99500))
        for: 3h
        labels:
          job: rss-inventory
          severity: warning
      - expr: |
          sum(rate(http_requests_total{job="rss-inventory",code=~"5.."}[1d]))
          /
          sum(rate(http_requests_total{job="rss-inventory"}[1d]))
        labels:
          job: rss-inventory
        record: http_requests_total:burnrate1d
      - expr: |
          sum(rate(http_requests_total{job="rss-inventory",code=~"5.."}[1h]))
          /
          sum(rate(http_requests_total{job="rss-inventory"}[1h]))
        labels:
          job: rss-inventory
        record: http_requests_total:burnrate1h
      - expr: |
          sum(rate(http_requests_total{job="rss-inventory",code=~"5.."}[2h]))
          /
          sum(rate(http_requests_total{job="rss-inventory"}[2h]))
        labels:
          job: rss-inventory
        record: http_requests_total:burnrate2h
      - expr: |
          sum(rate(http_requests_total{job="rss-inventory",code=~"5.."}[30m]))
          /
          sum(rate(http_requests_total{job="rss-inventory"}[30m]))
        labels:
          job: rss-inventory
        record: http_requests_total:burnrate30m
      - expr: |
          sum(rate(http_requests_total{job="rss-inventory",code=~"5.."}[3d]))
          /
          sum(rate(http_requests_total{job="rss-inventory"}[3d]))
        labels:
          job: rss-inventory
        record: http_requests_total:burnrate3d
      - expr: |
          sum(rate(http_requests_total{job="rss-inventory",code=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{job="rss-inventory"}[5m]))
        labels:
          job: rss-inventory
        record: http_requests_total:burnrate5m
      - expr: |
          sum(rate(http_requests_total{job="rss-inventory",code=~"5.."}[6h]))
          /
          sum(rate(http_requests_total{job="rss-inventory"}[6h]))
        labels:
          job: rss-inventory
        record: http_requests_total:burnrate6h
      #Latency rules start here in case we need to update
    - name: rss-inventory-SLOs-http_request_duration_seconds
      rules:
      - alert: LatencyBudgetBurn
        annotations:
          message: 'High requests latency budget burn for job=rss-inventory,latency=1.2 (current value: {{ $value }})'
        expr: |
          (
            latencytarget:http_request_duration_seconds:rate1h{job="rss-inventory",latency="1.2"} > (14.4*(1.0-0.99500))
            and
            latencytarget:http_request_duration_seconds:rate5m{job="rss-inventory",latency="1.2"} > (14.4*(1.0-0.99500))
          )
          or
          (
            latencytarget:http_request_duration_seconds:rate6h{job="rss-inventory",latency="1.2"} > (6*(1.0-0.99500))
            and
            latencytarget:http_request_duration_seconds:rate30m{job="rss-inventory",latency="1.2"} > (6*(1.0-0.99500))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
          severity: critical
      - alert: LatencyBudgetBurn
        annotations:
          message: 'High requests latency budget burn for job=rss-inventory,latency=1.2 (current value: {{ $value }})'
        expr: |
          (
            latencytarget:http_request_duration_seconds:rate1d{job="rss-inventory",latency="1.2"} > (3*(1.0-0.99500))
            and
            latencytarget:http_request_duration_seconds:rate2h{job="rss-inventory",latency="1.2"} > (3*(1.0-0.99500))
          )
          or
          (
            latencytarget:http_request_duration_seconds:rate3d{job="rss-inventory",latency="1.2"} > (1.0-0.99500)
            and
            latencytarget:http_request_duration_seconds:rate6h{job="rss-inventory",latency="1.2"} > (1.0-0.99500)
          )
        labels:
          job: rss-inventory
          latency: "1.2"
          severity: warning
      - expr: |
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="rss-inventory",le="1.2",code!~"5.."}[5m]))
            /
            sum(rate(http_request_duration_seconds_count{job="rss-inventory"}[5m]))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
        record: latencytarget:http_request_duration_seconds:rate5m
      - expr: |
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="rss-inventory",le="1.2",code!~"5.."}[30m]))
            /
            sum(rate(http_request_duration_seconds_count{job="rss-inventory"}[30m]))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
        record: latencytarget:http_request_duration_seconds:rate30m
      - expr: |
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="rss-inventory",le="1.2",code!~"5.."}[1h]))
            /
            sum(rate(http_request_duration_seconds_count{job="rss-inventory"}[1h]))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
        record: latencytarget:http_request_duration_seconds:rate1h
      - expr: |
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="rss-inventory",le="1.2",code!~"5.."}[2h]))
            /
            sum(rate(http_request_duration_seconds_count{job="rss-inventory"}[2h]))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
        record: latencytarget:http_request_duration_seconds:rate2h
      - expr: |
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="rss-inventory",le="1.2",code!~"5.."}[6h]))
            /
            sum(rate(http_request_duration_seconds_count{job="rss-inventory"}[6h]))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
        record: latencytarget:http_request_duration_seconds:rate6h
      - expr: |
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="rss-inventory",le="1.2",code!~"5.."}[1d]))
            /
            sum(rate(http_request_duration_seconds_count{job="rss-inventory"}[1d]))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
        record: latencytarget:http_request_duration_seconds:rate1d
      - expr: |
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="rss-inventory",le="1.2",code!~"5.."}[3d]))
            /
            sum(rate(http_request_duration_seconds_count{job="rss-inventory"}[3d]))
          )
        labels:
          job: rss-inventory
          latency: "1.2"
        record: latencytarget:http_request_duration_seconds:rate3d
