apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rss-inventory-prometheus-rules
  namespace: rss-inventory
  labels:
    app: rss-inventory
    job: rss-inventory-service
    release: kube-prometheus-stack
    app: kube-prometheus-stack
    team: sre
spec:
  groups: 
  - name: rssunventorySLOs-http_requests_total
    rules:
    - alert: RSSInventory:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-inventory-service (current value: {{ $value }})'
      expr: |
        sum(RSSInventory:http_request_error_count:burnrate5m{job="rss-inventory-service"}) > (14.40 * (1-0.99500))
        and
        sum(RSSInventory:http_request_error_count:burnrate1h{job="rss-inventory-service"}) > (14.40 * (1-0.99500))
      for: 2m
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
        severity: page
    - alert: RSSInventory:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-inventory-service (current value: {{ $value }})'
      expr: |
        sum(RSSInventory:http_request_error_count:burnrate30m{job="rss-inventory-service"}) > (6.00 * (1-0.99500))
        and
        sum(RSSInventory:http_request_error_count:burnrate6h{job="rss-inventory-service"}) > (6.00 * (1-0.99500))
      for: 15m
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
        severity: page
    - alert: RSSInventory:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-inventory-service (current value: {{ $value }})'
      expr: |
        sum(RSSInventory:http_request_error_count:burnrate2h{job="rss-inventory-service"}) > (3.00 * (1-0.99500))
        and
        sum(RSSInventory:http_request_error_count:burnrate1d{job="rss-inventory-service"}) > (3.00 * (1-0.99500))
      for: 1h
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
        severity: ticket
    - alert: RSSInventory:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-inventory-service (current value: {{ $value }})'
      expr: |
        sum(RSSInventory:http_request_error_count:burnrate6h{job="rss-inventory-service"}) > (1.00 * (1-0.99500))
        and
        sum(RSSInventory:http_request_error_count:burnrate3d{job="rss-inventory-service"}) > (1.00 * (1-0.99500))
      for: 3h
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
        severity: ticket
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*", status=~"5.."}[1d]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service"}[1d]))
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
      record: RSSInventory:http_request_error_count:burnrate1d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*", status=~"5.."}[1h]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service"}[1h]))
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
      record: RSSInventory:http_request_error_count:burnrate1h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*", status=~"5.."}[2h]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service"}[2h]))
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
      record: RSSInventory:http_request_error_count:burnrate2h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*", status=~"5.."}[30m]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service"}[30m]))
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
      record: RSSInventory:http_request_error_count:burnrate30m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*", status=~"5.."}[3d]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service"}[3d]))
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
      record: RSSInventory:http_request_error_count:burnrate3d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*", status=~"5.."}[5m]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service"}[5m]))
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
      record: RSSInventory:http_request_error_count:burnrate5m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*", status=~"5.."}[6h]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-inventory-service", url!~"/actuator/.*"}[6h]))
      labels:
        app: rss-inventory
        job: rss-inventory-service
        release: kube-prometheus-stack
      record: RSSInventory:http_request_error_count:burnrate6h