name: BUILD
on:
  push:
    branches:
      - dev
env:
  ECR_REPOSITORY_PREFIX: ${{ secrets.ECR_REPOSITORY_PREFIX }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PREFIX }}-${{ secrets.APP_NAME }}
  IMAGE_TAG: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }} # new for handoffOne branch
  JENKINS_USER: inventory_service
  NAMESPACE: rss-inventory
  CONTAINER: rss-inventory-service
jobs:
  sonar_maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven and Sonar
        run: |
          cd ./$PROJECT_ROOT 
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # ---[ Configuring AWS credentials and Logging in to ECR ]---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.EKS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EKS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build the image
        id: docker_build
        run: |
          cd ./$PROJECT_ROOT  
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest           
  access_aws_set_loadtest_deployment:
    needs: [sonar_maven_build]
    runs-on: ubuntu-latest
    steps:
      - name: access AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.EKS_ACCESS_KEY_ID }} --profile p3
          aws configure set aws_secret_access_key ${{ secrets.EKS_SECRET_ACCESS_KEY }} --profile p3
          aws configure set default.region ${{ secrets.AWS_REGION }} --profile p3
          aws eks --region us-east-1 update-kubeconfig --profile p3 --name ${{ secrets.EKS_CLUSTER_NAME }}
          kubectl --namespace $NAMESPACE set image deployment/$NAMESPACE-service-deployment-load-test $CONTAINER=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl --namespace $NAMESPACE scale --replicas=3 deployment/$NAMESPACE-service-deployment-load-test
  handoff_to_jenkins:
    needs: [access_aws_set_loadtest_deployment]
    name: Handoff to Jenkins for load testing
    runs-on: ubuntu-latest
    steps:
      - name: handoff
        run: |
          curl -X POST http://$JENKINS_USER:$JENKINS_TOKEN@ad8d6edfec9aa4a79be8f07ba490356a-1499412652.us-east-1.elb.amazonaws.com/jenkins/job/InvServLoadTestAndDeployCanary/build?token=load_test
